[1/5] cd /home/lotanna/Documents/wifi_driver/wifi_driver/build/esp-idf/esptool_py && /home/lotanna/.espressif/python_env/idf5.4_py3.12_env/bin/python /home/lotanna/esp/esp-idf/components/partition_table/check_sizes.py --offset 0x8000 partition --type app /home/lotanna/Documents/wifi_driver/wifi_driver/build/partition_table/partition-table.bin /home/lotanna/Documents/wifi_driver/wifi_driver/build/wifi_driver.bin
wifi_driver.bin binary size 0x2b9c0 bytes. Smallest app partition is 0x100000 bytes. 0xd4640 bytes (83%) free.
[2/5] Performing build step for 'bootloader'
[1/1] cd /home/lotanna/Documents/wifi_driver/wifi_driver/build/bootloader/esp-idf/esptool_py && /home/lotanna/.espressif/python_env/idf5.4_py3.12_env/bin/python /home/lotanna/esp/esp-idf/components/partition_table/check_sizes.py --offset 0x8000 bootloader 0x1000 /home/lotanna/Documents/wifi_driver/wifi_driver/build/bootloader/bootloader.bin
Bootloader binary size 0x6580 bytes. 0xa80 bytes (9%) free.
[3/5] No install step for 'bootloader'
[4/5] Completed 'bootloader'
[4/5] cd /home/lotanna/esp/esp-idf/components/esptool_py && /usr/bin/cmake -D IDF_PATH=/home/lotanna/esp/esp-idf -D "SERIAL_TOOL=/home/lotanna/.espressif/python_env/idf5.4_py3.12_env/bin/python;;/home/lotanna/esp/esp-idf/components/esptool_py/esptool/esptool.py;--chip;esp32" -D "SERIAL_TOOL_ARGS=--before=default_reset;--after=hard_reset;write_flash;@flash_args" -D WORKING_DIRECTORY=/home/lotanna/Documents/wifi_driver/wifi_driver/build -P /home/lotanna/esp/esp-idf/components/esptool_py/run_serial_tool.cmake
esptool.py --chip esp32 -p /dev/ttyUSB0 -b 460800 --before=default_reset --after=hard_reset write_flash --flash_mode dio --flash_freq 40m --flash_size 2MB 0x1000 bootloader/bootloader.bin 0x10000 wifi_driver.bin 0x8000 partition_table/partition-table.bin
esptool.py v4.8.1
Serial port /dev/ttyUSB0

A fatal error occurred: Could not open /dev/ttyUSB0, the port is busy or doesn't exist.
([Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0')

Hint: Check if the port is correct and ESP connected

FAILED: CMakeFiles/flash /home/lotanna/Documents/wifi_driver/wifi_driver/build/CMakeFiles/flash 
cd /home/lotanna/esp/esp-idf/components/esptool_py && /usr/bin/cmake -D IDF_PATH=/home/lotanna/esp/esp-idf -D "SERIAL_TOOL=/home/lotanna/.espressif/python_env/idf5.4_py3.12_env/bin/python;;/home/lotanna/esp/esp-idf/components/esptool_py/esptool/esptool.py;--chip;esp32" -D "SERIAL_TOOL_ARGS=--before=default_reset;--after=hard_reset;write_flash;@flash_args" -D WORKING_DIRECTORY=/home/lotanna/Documents/wifi_driver/wifi_driver/build -P /home/lotanna/esp/esp-idf/components/esptool_py/run_serial_tool.cmake
ninja: build stopped: subcommand failed.
